### ISSUE TITLE
Unable to correct erasures

### ISSUE THREAD

**Issue by hivenet-mathieu-lacage** [tomerfiliba-org/reedsolomon#79]
Hi,

I have data encoded with  https://github.com/klauspost/reedsolomon and I would like to decode it with this python library.

The objective of the following test code is to shard the input data with 3 parity shards for each data shard and drop one random shard: my expectation is that the decoder should be able to reconstruct the original data.

```
import random

import reedsolo


def encode(data, n_data_shards, n_parity_shards):
    shard_size = int((len(data) + n_data_shards - 1) / n_data_shards)
    rss = reedsolo.RSCodec(
        nsym=n_parity_shards,
        nsize=n_parity_shards+n_data_shards
    )
    encoded = rss.encode(data)
    result = [encoded[i*shard_size:(i+1)*shard_size] for i in range(n_data_shards+n_parity_shards)]
    return result


def decode(shards, n_data_shards, n_parity_shards):
    shard_size = None
    for i, shard in enumerate(shards):
        if shard is not None:
            if shard_size is None:
                shard_size = len(shard)
            elif shard_size != len(shard):
                assert i == len(shards)-1
    assert len(shards) == n_data_shards + n_parity_shards
    erase_pos = []
    for i, shard in enumerate(shards):
        if shard is None:
            erase_pos.extend([i*shard_size+j for j in range(shard_size)])
    n_missing = len([shard for shard in shards if shard is None])
    assert n_missing <= n_parity_shards
    
    rss = reedsolo.RSCodec(
        nsym=n_parity_shards,
        nsize=n_parity_shards+n_data_shards
    )
    zeroes = b'\0'*shard_size
    data = [shard if shard is not None else zeroes for shard in shards]
    result = rss.decode(b''.join(data),  erase_pos=erase_pos)
    return result[0]


def test_drop_random(ndrop, ndata, nparity):
    data = random.randbytes(100)
    encoded = encode(data, ndata, nparity)
    indexes = list(range(len(encoded)))
    random.shuffle(indexes)
    for drop in indexes[:ndrop]:
        encoded[drop] = None
    print(encoded)
    decoded = decode(encoded, ndata, nparity)
    assert encoded == decoded

test_drop_random(1, 1, 3)

```

This results in this:
```
Traceback (most recent call last):
  File "/home/mathieu/code/agent-swarm-upstream/./test.py", line 66, in <module>
    test_drop_random(1, 1, 3)
  File "/home/mathieu/code/agent-swarm-upstream/./test.py", line 63, in test_drop_random
    decoded = decode(encoded, ndata, nparity)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mathieu/code/agent-swarm-upstream/./test.py", line 39, in decode
    result = rss.decode(b''.join(data),  erase_pos=erase_pos)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mathieu/.local/lib/python3.12/site-packages/reedsolo.py", line 929, in decode
    rmes, recc, errata_pos = rs_correct_msg(chunk, nsym, fcr=self.fcr, generator=self.generator, erase_pos=e_pos, only_erasures=only_erasures)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mathieu/.local/lib/python3.12/site-packages/reedsolo.py", line 734, in rs_correct_msg
    if len(erase_pos) > nsym: raise ReedSolomonError("Too many erasures to correct")
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
reedsolo.ReedSolomonError: Too many erasures to correct
```

So, it tells me that there are too many errors but, I dropped only 1 shard out of 1+3=4 so, I would expect the code to be able to recover. 

Is there something I do not understand about the way this library works ?

**Comment by hivenet-mathieu-lacage** [comment]
For the record, I eventually found out that what I was trying to do was called "erasure coding" and there are other libraries better focused on handling that use-case. zfec did the job for me. I also tried pyeclib which was limited to handling combinations of data+parity < 32.

Sorry for the noise.
